# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdscritaA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrganoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('Deca', 'Decanato'), ('Divi', 'División'), ('Otro', 'Otro')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^([A-Z0-9]){6}$')])),
                ('denominacion', models.CharField(max_length=40)),
                ('fecha_periodo', models.CharField(choices=[('EM', 'Enero-Marzo'), ('AJ', 'Abril-Julio'), ('VE', 'Verano'), ('SD', 'Septiembre-Diciembre')], max_length=2)),
                ('fecha_año', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1967)])),
                ('horas_teoria', models.PositiveSmallIntegerField()),
                ('horas_practica', models.PositiveSmallIntegerField()),
                ('horas_laboratorio', models.PositiveSmallIntegerField()),
                ('creditos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(16)])),
                ('objetivos', models.TextField()),
                ('contenidos_sinopticos', models.TextField()),
                ('estrategias_metodologicas', models.TextField()),
                ('estrategias_evaluacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaBibliografica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='programa',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.UnidadAcademica'),
        ),
        migrations.AddField(
            model_name='adscritaa',
            name='organo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.OrganoAcademico'),
        ),
        migrations.AddField(
            model_name='adscritaa',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.UnidadAcademica'),
        ),
    ]
