# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 03:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ocr.models
import ocr.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='El nombre completo de la unidad académica', max_length=40, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'instancia',
                'verbose_name_plural': 'instancias',
            },
        ),
        migrations.CreateModel(
            name='PDFAnonimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(help_text='El PDF del programa a analizar', upload_to='tmp', validators=[ocr.validators.validate_pdf_ext_mime], verbose_name='pdf')),
                ('tipo', models.CharField(choices=[('T', 'Texto'), ('I', 'Imagen')], help_text='El tipo de PDF a analizar', max_length=1, verbose_name='tipo')),
                ('texto', models.TextField(blank=True, help_text='El texto extraído del PDF', verbose_name='texto extraído')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='El código de la materia', max_length=6, validators=[django.core.validators.RegexValidator(regex='^([A-Z0-9]){6}$')], verbose_name='código')),
                ('denominacion', models.CharField(help_text='El nombre completo de la materia', max_length=100, verbose_name='nombre')),
                ('fecha_periodo', models.CharField(choices=[('1', 'ene-mar'), ('2', 'abr-jul'), ('3', 'intensivo'), ('4', 'sep-dic')], help_text='El trimestre cuando entra en vigencia el programa', max_length=1, verbose_name='trimestre')),
                ('fecha_año', models.PositiveSmallIntegerField(help_text='El año cuando entra en vigencia el programa', validators=[django.core.validators.MinValueValidator(1969)], verbose_name='año')),
                ('horas_teoria', models.PositiveSmallIntegerField(help_text='El número de horas de teoría semanales', verbose_name='horas de teoría')),
                ('horas_practica', models.PositiveSmallIntegerField(help_text='El número de horas de práctica semanales', verbose_name='horas de práctica')),
                ('horas_laboratorio', models.PositiveSmallIntegerField(help_text='El número de horas de laboratorio semanales', verbose_name='horas de laboratorio')),
                ('creditos', models.PositiveSmallIntegerField(help_text='La cantidad de créditos que vale la materia', validators=[django.core.validators.MaxValueValidator(16)], verbose_name='créditos')),
                ('objetivos', models.TextField(help_text='Los objetivos de la materia', verbose_name='objetivos')),
                ('contenidos_sinopticos', models.TextField(help_text='Resumen del contenido de la materia', verbose_name='contenido')),
                ('estrategias_metodologicas', models.TextField(help_text='Las estratégias metodológicas de enseñanza utilizadas', verbose_name='estretegias metodológicas')),
                ('estrategias_evaluacion', models.TextField(help_text='Las estrategias de evaluación utilizadas', verbose_name='estrategias de evaluación')),
                ('requisito', models.TextField(help_text='Requisitos para cursar la materia', verbose_name='requisito')),
                ('pdf', models.FileField(help_text='El PDF del programa a analizar', upload_to=ocr.models.Programa.determinar_lugar, verbose_name='pdf')),
                ('instancia', models.ForeignKey(help_text='Instancia responsable por la asignatura', on_delete=django.db.models.deletion.CASCADE, to='ocr.Instancia', verbose_name='instancia')),
            ],
            options={
                'verbose_name': 'programa',
            },
        ),
        migrations.CreateModel(
            name='Programa_Borrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='El código de la materia', max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='^([A-Z0-9]){6}$')], verbose_name='código')),
                ('denominacion', models.CharField(blank=True, help_text='El nombre completo de la materia', max_length=100, null=True, verbose_name='nombre')),
                ('fecha_periodo', models.CharField(blank=True, choices=[('1', 'ene-mar'), ('2', 'abr-jul'), ('3', 'intensivo'), ('4', 'sep-dic')], help_text='El trimestre cuando entra en vigencia el programa', max_length=1, null=True, verbose_name='trimestre')),
                ('fecha_año', models.PositiveSmallIntegerField(blank=True, help_text='El año cuando entra en vigencia el programa', null=True, validators=[django.core.validators.MinValueValidator(1969)], verbose_name='año')),
                ('horas_teoria', models.PositiveSmallIntegerField(blank=True, help_text='El número de horas de teoría semanales', null=True, verbose_name='horas de teoría')),
                ('horas_practica', models.PositiveSmallIntegerField(blank=True, help_text='El número de horas de práctica semanales', null=True, verbose_name='horas de práctica')),
                ('horas_laboratorio', models.PositiveSmallIntegerField(blank=True, help_text='El número de horas de laboratorio semanales', null=True, verbose_name='horas de laboratorio')),
                ('creditos', models.PositiveSmallIntegerField(blank=True, help_text='La cantidad de créditos que vale la materia', null=True, validators=[django.core.validators.MaxValueValidator(16)], verbose_name='créditos')),
                ('objetivos', models.TextField(blank=True, help_text='Los objetivos de la materia', null=True, verbose_name='objetivos')),
                ('contenidos_sinopticos', models.TextField(blank=True, help_text='Resumen del contenido de la materia', null=True, verbose_name='contenido')),
                ('estrategias_metodologicas', models.TextField(blank=True, help_text='Las estratégias metodológicas de enseñanza utilizadas', null=True, verbose_name='estretegias metodológicas')),
                ('estrategias_evaluacion', models.TextField(blank=True, help_text='Las estrategias de evaluación utilizadas', null=True, verbose_name='estrategias de evaluación')),
                ('pdf', models.FileField(help_text='El PDF del programa a analizar', upload_to=ocr.models.Programa_Borrador.determinar_lugar, verbose_name='pdf')),
                ('Instancia', models.ForeignKey(help_text='Instancia responsable por la asignatura', on_delete=django.db.models.deletion.CASCADE, to='ocr.Instancia', verbose_name='instancia')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaBibliografica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Una fuente bibliográfica recomendada', max_length=500, verbose_name='referencia')),
                ('programa', models.ForeignKey(help_text='El prgrama que la recomienda', on_delete=django.db.models.deletion.CASCADE, to='ocr.Programa', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'referencia',
                'verbose_name_plural': 'referencias',
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='referenciabibliografica',
            order_with_respect_to='programa',
        ),
        migrations.AlterUniqueTogether(
            name='programa',
            unique_together=set([('codigo', 'fecha_periodo', 'fecha_año')]),
        ),
    ]
