# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adscritaa',
            name='organo',
        ),
        migrations.RemoveField(
            model_name='adscritaa',
            name='unidad',
        ),
        migrations.AlterModelOptions(
            name='organoacademico',
            options={'verbose_name': 'organo académico', 'verbose_name_plural': 'organos académicos'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['departamento', 'fecha_año', 'fecha_periodo'], 'verbose_name': 'programa'},
        ),
        migrations.AlterModelOptions(
            name='referenciabibliografica',
            options={'verbose_name': 'referencia', 'verbose_name_plural': 'referencias'},
        ),
        migrations.AlterModelOptions(
            name='requisito',
            options={'verbose_name': 'requisito', 'verbose_name_plural': 'requisitos'},
        ),
        migrations.AlterModelOptions(
            name='unidadacademica',
            options={'verbose_name': 'unidad académica', 'verbose_name_plural': 'unidades académicas'},
        ),
        migrations.AddField(
            model_name='unidadacademica',
            name='organo',
            field=models.ManyToManyField(to='ocr.OrganoAcademico'),
        ),
        migrations.AlterField(
            model_name='organoacademico',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_periodo',
            field=models.CharField(choices=[('1', 'Enero-Marzo'), ('2', 'Abril-Julio'), ('3', 'Verano'), ('4', 'Septiembre-Diciembre')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='programa',
            unique_together=set([('codigo', 'fecha_periodo', 'fecha_año')]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='referenciabibliografica',
            order_with_respect_to='programa',
        ),
        migrations.AlterOrderWithRespectTo(
            name='requisito',
            order_with_respect_to='programa',
        ),
        migrations.DeleteModel(
            name='AdscritaA',
        ),
        migrations.AlterOrderWithRespectTo(
            name='unidadacademica',
            order_with_respect_to='organo',
        ),
    ]
