# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 07:08
from __future__ import unicode_literals

from django.db import migrations

from ocr.models import Instancia
from ocr.models import Decanato

import os.path, os
import shutil

def load_stores_from_fixture(apps, schema_editor):
    from django.core.management import call_command

    call_command("loaddata", "decanato")
    call_command("loaddata", "instancia")
    if os.path.isdir('media'):
        shutil.rmtree('media')
    for x in Instancia.objects.all():
        x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_stores_from_fixture),
    ]