# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 03:50
from __future__ import unicode_literals

from django.db import migrations

def load_stores_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "instancia")

class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_stores_from_fixture),
    ]
