# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20170315_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorreferencia',
            name='referencia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ocr.ReferenciaBibliografica', verbose_name='referencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa_borrador',
            name='objetivosE',
            field=models.TextField(blank=True, help_text='Los objetivos específicos de la materia', null=True, verbose_name='objetivos específicos'),
        ),
        migrations.AlterField(
            model_name='programa_borrador',
            name='objetivos',
            field=models.TextField(blank=True, help_text='Los objetivos generales de la materia', null=True, verbose_name='objetivos generales'),
        ),
    ]
