# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20170314_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciabibliografica',
            name='programa',
            field=models.ForeignKey(help_text='El prgrama que la recomienda', on_delete=django.db.models.deletion.CASCADE, to='ocr.Programa_Borrador', verbose_name='programa'),
        ),
    ]
