# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20170303_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_borrador',
            name='texto',
            field=models.TextField(blank=True, help_text='El texto extraído del PDF', verbose_name='texto extraído'),
        ),
    ]
