# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import ocr.models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20170214_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='upload',
            field=models.FileField(default='', upload_to=ocr.models.Programa.determinar_lugar),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organoacademico',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='texto',
            field=models.CharField(max_length=500),
        ),
    ]
