# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20170314_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='contenidos_sinopticos',
            field=models.TextField(help_text='Resumen del contenido de la materia', verbose_name='contenido sinóptico'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='estrategias_metodologicas',
            field=models.TextField(help_text='Las estratégias metodológicas de enseñanza utilizadas', verbose_name='estrategias metodológicas'),
        ),
        migrations.AlterField(
            model_name='programa_borrador',
            name='contenidos_sinopticos',
            field=models.TextField(blank=True, help_text='Resumen del contenido de la materia', null=True, verbose_name='contenido sinóptico'),
        ),
        migrations.AlterField(
            model_name='programa_borrador',
            name='estrategias_metodologicas',
            field=models.TextField(blank=True, help_text='Las estratégias metodológicas de enseñanza utilizadas', null=True, verbose_name='estrategias metodológicas'),
        ),
    ]
