# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20170214_1825'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='unidadacademica',
            order_with_respect_to=None,
        ),
    ]
