# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20170316_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa_borrador',
            name='horas_laboratorio',
            field=models.PositiveSmallIntegerField(default=0, help_text='El número de horas de laboratorio semanales', verbose_name='horas de laboratorio'),
        ),
        migrations.AlterField(
            model_name='programa_borrador',
            name='horas_practica',
            field=models.PositiveSmallIntegerField(default=0, help_text='El número de horas de práctica semanales', verbose_name='horas de práctica'),
        ),
        migrations.AlterField(
            model_name='programa_borrador',
            name='horas_teoria',
            field=models.PositiveSmallIntegerField(default=0, help_text='El número de horas de teoría semanales', verbose_name='horas de teoría'),
        ),
    ]
