# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_auto_20170314_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, help_text='La descripción del campo adicional', verbose_name='descripción')),
                ('programa', models.ForeignKey(help_text='El programa asociado', null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.Programa', verbose_name='programa')),
                ('programa_borrador', models.ForeignKey(help_text='El programa asociado', null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.Programa_Borrador', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'descripción de campo adicional',
            },
        ),
        migrations.CreateModel(
            name='TipoCampoAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='El nombre completo del campo adicional', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'campo adicional',
            },
        ),
        migrations.AddField(
            model_name='referenciabibliografica',
            name='programa_borrador',
            field=models.ForeignKey(help_text='El programa que la recomienda', null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.Programa_Borrador', verbose_name='programa'),
        ),
        migrations.AlterField(
            model_name='referenciabibliografica',
            name='programa',
            field=models.ForeignKey(help_text='El programa que la recomienda', null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.Programa', verbose_name='programa'),
        ),
        migrations.AddField(
            model_name='campoadicional',
            name='tipo_campo_adicional',
            field=models.ForeignKey(help_text='tipo de campo adicional', null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.TipoCampoAdicional', verbose_name='campo adicional'),
        ),
    ]
