# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_auto_20170317_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='requisito',
        ),
        migrations.AddField(
            model_name='programa',
            name='objetivosE',
            field=models.TextField(blank=True, help_text='Los objetivos específicos de la materia', null=True, verbose_name='objetivos específicos'),
        ),
        migrations.AddField(
            model_name='programa',
            name='texto',
            field=models.TextField(blank=True, help_text='El texto extraído del PDF', verbose_name='texto extraído'),
        ),
        migrations.AddField(
            model_name='programa_borrador',
            name='published',
            field=models.BooleanField(default=False, help_text='Ya es un PA completo y no editable?', verbose_name='publicado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programa',
            name='contenidos_sinopticos',
            field=models.TextField(blank=True, help_text='Resumen del contenido de la materia', null=True, verbose_name='contenido sinóptico'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='creditos',
            field=models.PositiveSmallIntegerField(blank=True, help_text='La cantidad de créditos que vale la materia', null=True, validators=[django.core.validators.MaxValueValidator(16)], verbose_name='créditos'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='denominacion',
            field=models.CharField(blank=True, help_text='El nombre completo de la materia', max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='estrategias_evaluacion',
            field=models.TextField(blank=True, help_text='Las estrategias de evaluación utilizadas', null=True, verbose_name='estrategias de evaluación'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='estrategias_metodologicas',
            field=models.TextField(blank=True, help_text='Las estratégias metodológicas de enseñanza utilizadas', null=True, verbose_name='estrategias metodológicas'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='horas_laboratorio',
            field=models.PositiveSmallIntegerField(default=0, help_text='El número de horas de laboratorio semanales', verbose_name='horas de laboratorio'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='horas_practica',
            field=models.PositiveSmallIntegerField(default=0, help_text='El número de horas de práctica semanales', verbose_name='horas de práctica'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='horas_teoria',
            field=models.PositiveSmallIntegerField(default=0, help_text='El número de horas de teoría semanales', verbose_name='horas de teoría'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='objetivos',
            field=models.TextField(blank=True, help_text='Los objetivos generales de la materia', null=True, verbose_name='objetivos generales'),
        ),
    ]
