# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 02:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ocr.models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_auto_20170214_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organoacademico',
            options={'verbose_name': 'órgano académico', 'verbose_name_plural': 'órganos académicos'},
        ),
        migrations.AlterField(
            model_name='organoacademico',
            name='nombre',
            field=models.CharField(help_text='El nombre completo del órgano académico', max_length=70, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='organoacademico',
            name='tipo',
            field=models.CharField(choices=[('Deca', 'Decanato'), ('Divi', 'División'), ('Otro', 'Otro')], help_text='El tipo de órgano académico (decanato, división, etc.)', max_length=4, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='codigo',
            field=models.CharField(help_text='El código de la materia', max_length=6, validators=[django.core.validators.RegexValidator(regex='^([A-Z0-9]){6}$')], verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='contenidos_sinopticos',
            field=models.TextField(help_text='Resumen del contenido de la materia', verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='creditos',
            field=models.PositiveSmallIntegerField(help_text='La cantidad de créditos que vale la materia', validators=[django.core.validators.MaxValueValidator(16)], verbose_name='créditos'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='denominacion',
            field=models.CharField(help_text='El nombre completo de la materia', max_length=40, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='departamento',
            field=models.ForeignKey(help_text='El departamento responsable por la asignatura', on_delete=django.db.models.deletion.CASCADE, to='ocr.UnidadAcademica', verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='estrategias_evaluacion',
            field=models.TextField(help_text='Las estrategias de evaluación utilizadas', verbose_name='estrategias de evaluación'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='estrategias_metodologicas',
            field=models.TextField(help_text='Las estratégias metodológicas de enseñanza utilizadas', verbose_name='estretegias metodológicas'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_año',
            field=models.PositiveSmallIntegerField(help_text='El año cuando entra en vigencia el programa', validators=[django.core.validators.MinValueValidator(1967)], verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_periodo',
            field=models.CharField(choices=[('1', 'Enero-Marzo'), ('2', 'Abril-Julio'), ('3', 'Verano'), ('4', 'Septiembre-Diciembre')], help_text='El trimestre cuando entra en vigencia el programa', max_length=1, verbose_name='trimestre'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='horas_laboratorio',
            field=models.PositiveSmallIntegerField(help_text='El número de horas de laboratorio semanales', verbose_name='horas de laboratorio'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='horas_practica',
            field=models.PositiveSmallIntegerField(help_text='El número de horas de práctica semanales', verbose_name='horas de práctica'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='horas_teoria',
            field=models.PositiveSmallIntegerField(help_text='El número de horas de teoría semanales', verbose_name='horas de teoría'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='objetivos',
            field=models.TextField(help_text='Los objetivos de la materia', verbose_name='objetivos'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='pdf',
            field=models.FileField(help_text='El PDF del programa a analizar', upload_to=ocr.models.Programa.determinar_lugar, verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='referenciabibliografica',
            name='programa',
            field=models.ForeignKey(help_text='El prgrama que la recomienda', on_delete=django.db.models.deletion.CASCADE, to='ocr.Programa', verbose_name='programa'),
        ),
        migrations.AlterField(
            model_name='referenciabibliografica',
            name='texto',
            field=models.CharField(help_text='Una fuente bibliográfica recomendada', max_length=500, verbose_name='referencia'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='programa',
            field=models.ForeignKey(help_text='El programa de la asignatura que lo requiere', on_delete=django.db.models.deletion.CASCADE, to='ocr.Programa', verbose_name='programa'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='texto',
            field=models.CharField(help_text='Un requisito de la asignatura (para un programa específico)', max_length=500, verbose_name='requisito'),
        ),
        migrations.AlterField(
            model_name='unidadacademica',
            name='nombre',
            field=models.CharField(help_text='El nombre completo de la unidad académica', max_length=40, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='unidadacademica',
            name='organo',
            field=models.ManyToManyField(help_text='Relación de pertencia a órgano académico', to='ocr.OrganoAcademico', verbose_name='organos'),
        ),
    ]
