# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_auto_20170215_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAnonimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(help_text='El PDF del programa a analizar', upload_to='tmp', verbose_name='pdf')),
                ('tipo', models.CharField(choices=[('T', 'Texto'), ('I', 'Imagen')], help_text='El tipo de PDF a analizar', max_length=1, verbose_name='tipo')),
                ('texto', models.TextField(help_text='El texto extraído del PDF', verbose_name='texto extraído')),
            ],
        ),
    ]
