# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_pdfanonimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'verbose_name': 'programa'},
        ),
        migrations.AlterField(
            model_name='unidadacademica',
            name='organo',
            field=models.ManyToManyField(help_text='Relación de pertencia a órgano académico', related_name='adscritoa', to='ocr.OrganoAcademico', verbose_name='organos'),
        ),
    ]
